### ISSUE TITLE
Using multiple quads?

### ISSUE THREAD

**Issue by celikomerdev** [ColinLeung-NiloCat/UnityURP-BillboardLensFlareShader#1]
Hi Colin,
Thanks for the shader,

Is it possible to use output color from origin flare on child flares?
Something like origin flare is just defines visibility area by its vertex positions and not render anything, but using this vertex colors on some other sprites to achieve directional flare effect?
![Example](https://user-images.githubusercontent.com/52651787/87652571-0ea80600-c75d-11ea-8064-2e1adc7669c3.jpg)

**Comment by ColinLeung-NiloCat** [comment]
Will need RenderTexture/ComputeBuffer and C# for this effect. 
This shader alone can't do this because flares don't know each other.

One possible solution is to edit the shader to accept a world space pivot override(visibility point), so every flare will use the same point in world space to do depth test. But this will need C# also.

I can't think of any solution which can be done by shader alone, without C#.
